<a href="https://colab.research.google.com/github/min-gyeong-00/pytorch/blob/main/Pytorch_Basic_Tensor_Manipulation2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import torch
import numpy as np

#View(Reshape)
t=np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
ft=torch.FloatTensor(t)
print(ft.shape)

print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [22]:
#Squeeze -1없앰

ft=torch.FloatTensor([0,1,2])
print(ft)
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

#Unsqueeze
ft=torch.Tensor([0,1,2])
print(ft.shape)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

print(ft.view(1,-1))
print(ft.view(1,-1).shape)

print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)


tensor([0., 1., 2.])
torch.Size([3])
tensor([0., 1., 2.])
torch.Size([3])
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [25]:
#Type casting

lt=torch.LongTensor([1,2,3,4])
print(lt)

print(lt.float())
bt=torch.ByteTensor([True,False,False,True])
print(bt)

print(bt.long())
print(bt.float())


#Concatenate
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

#Stacking
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))

print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))

#Ones and Zeros
x=torch.FloatTensor([[0,1,2],[3,4,5]])
print(x)

print(torch.ones_like(x))
print(torch.zeros_like(x))

#In-place Operation
x=torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
