<a href="https://colab.research.google.com/github/min-gyeong-00/pytorch/blob/main/Tensor_Manipulation_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#2D Tensor (Typical Simple Setting) =(batch size,dim)
#3D Tensor (Typical Computer Vision)=(batch size, width, height)
#3D Tensor (Typical Natural Language Processing)=(batch size, length, dim)


import numpy as np
import torch

#1D Array with PyTorch
t=torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print (t)
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[-1])  
print(t[2:5],t[4:-1])
print(t[:2],t[3:])

#2D Array with Pytorch
t=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t)

print(t.dim())
print(t.shape)
print(t.size())
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])


tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [ ]:
#Broadcasting

#Same shape
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
print(m1+m2)

#Vector+Scalar
a1=torch.FloatTensor([[1,2]])
a2=torch.FloatTensor([3]) #3 ->[[3,3]]
print(a1+a2)

# 2x1 Vector + 1x2 Vector >>둘다 2x2 행렬로 바꾸어서 계산함
b1=torch.FloatTensor([[1,2]])
b2=torch.FloatTensor([[3],[4]])



#Multiplication vs Matrix Multiplication
m1=torch.FloatTensor([[1,2],[3,4]]) # 2x2
m2=torch.FloatTensor([[1],[2]]) # 2x1
print(m1.matmul(m2))
print(m1.mul(m2)) #broadcasting 으로 2x1 이 2x2 로 바뀌어서 계산됨

#Mean
t1=torch.FloatTensor([1,2])
print(t1.mean())

t2=torch.FloatTensor([[1,2],[3,4]])
print(t2)
print(t2.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))




tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor(1.5000)
tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([5.5000, 6.5000, 7.5000])
tensor([ 2.,  5.,  8., 11.])
tensor([ 2.,  5.,  8., 11.])


In [ ]:
#Sum
t=torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [ ]:
#Max and Argmax
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

print(t.max())
print(t.max(dim=0))
print(t.max(dim=0)[0])
print(t.max(dim=0)[1])
print(t.max(dim=1))
print(t.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])
tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
